services:
  bot:
    build: .
    env_file:
      - .env
    volumes:
      - ./bookclub.db:/app/bookclub.db
      - ./logs:/app/logs
      - ./bot_persistence:/app/bot_persistence
    restart: always
